### ISSUE TITLE
Typo in description "Complex" -> "Convex"

### ISSUE THREAD

**Issue by TomMD** [bgamari/optimization#2]
The .cabal indicates Boyd has made a book with the title "Complex Optimization"...

**Comment by TomMD** [comment]
Also, the linked tutorial is broken. I suggest simply linking the book's PDF.

**Comment by bgamari** [comment]
Thanks @TomMD, I'll fix these shortly!

**Comment by bgamari** [comment]
@TomMD, it's quite sad that videolectures seems to be so defunct. I've removed the references.
